-- Supabase Migration SQL

INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (1, '★★★★★★★★★★★★★★★', '★★★★★★★★★★★★★★★', '★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★', '''★★★★★★★★★★★★★★★');
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (2, 'A001', '㈜다안일렉트레이드', '113-86-29501', '의의수, 홍석원', NULL, '퓨즈, 퓨즈홀더', '김기태', '02-718-9788', 'kkt0912@daan.co.kr', '서울특별시 구로구 구로동 1258 중앙유통단지 나동4107호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (3, 'A002', '㈜엠케이아이엔에스', '206-86-14014', '홍순태', NULL, 'SPD, Terminal Block, 다이오드, 퓨즈, 퓨즈홀더, DC커넥터', '홍순태', '02-497-1337', NULL, '서울특별시 성동구 왕십리로 58 419호(FORHU)', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (4, 'A003', '에스제이전자', '765-32-00151', '이종혁', NULL, '케이블그랜드, 화재감지기', '이종혁', '070-7868-9550', NULL, '서울특별시 구로구 경인로53길 15, 바동 2425호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (5, 'A004', '㈜SA POWER', '138-81-60035', '손보영', NULL, 'DC차단기', '박용호', '031-427-4673', NULL, '경기도 수원시 권선구 권선로 308-18 305동 104호 204호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (6, 'A005', '에스콘이엔지', '032-555-5470', '함종복', NULL, ' AC SPD, 통신 SPD', '함종복', '032-555-5470', NULL, '인천광역시 부평구 부평대로 283 (청정동, 부평우림라이온스벨리8층 B동806호)', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (7, 'A006', '아르비젼', '123-86-44284', '손영숙', NULL, ' 접속모듈, 감시모듈, 화재컨버터', '김태형', '02-853-1095', NULL, '서울시 금천구 가산디지털1로 2, 6층 603,604,605호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (8, 'A007', '에버넷전자', '138-81-60035', '임윤성', NULL, 'Power Supply', '서용인', '02-2066-2288', NULL, '경기도 안양시 만안구 덕천로 54, 5층', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (9, 'A008', '금산엠엔이', '106-81-44042', '고박', NULL, '케이블엔트리', '조범석', '02-804-9666', NULL, '서울시 금천구 시흥대로 281, 506호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (10, 'A009', '위트솔루션즈', '639-81-00700', '정차리', NULL, '벤트플러그', '이동근', '02-2054-8688', NULL, '서울시 송파구 송파대로 167, 에이동 4층 404호', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (11, 'A010', '소코코리아', '109-86-30940', '김길섭', NULL, '케이블엔트리', '이중곤', '02-2104-6592', NULL, '서울시 금천구 두산로 70(독산동, 현대지식산업센터 A동 2106호)', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (12, 'A011', '스토브리코리아', '502-86-08496', '김문석, 김정훈', NULL, '모듈커넥터(MC4)', '모윤준', '053-753-0075', NULL, '대구 달서구 달서대로 559, 1306호(이앤씨이노비즈타워)', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (13, 'A012', '유수', '143-81-04317', '김영기', NULL, '방열판', '맹용기', '031-378-9592', NULL, '경기도 화성시 향남읍 토성로 369-7', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (14, 'A013', '고려화공', '603-81-10704', '조영준', NULL, '자동소화장치', '박재윤', '051-256-7383', NULL, '부산광역시 서구 충무대로 264', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (15, 'A014', '지로이아이', '142-81-53227', '김근배, 민경환', NULL, '열푼포 센서', '김상규', '031-285-1133', NULL, '경기도 용인시 기흥구 덕영대로 1753, 나동(하갈동)', NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (16, 'A015', '성지티앤엠', NULL, NULL, NULL, '노드락', '오세영', '031-298-3248', NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (17, 'A016', '도마산전', NULL, '김희철', NULL, '소형차단기', '김희철', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (18, 'A017', '오포산업', NULL, NULL, NULL, '부스바', '김수규', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (19, 'A018', '에이젠코리아', NULL, NULL, NULL, '부스바', '구도영', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (20, 'A019', '현대파워', NULL, NULL, NULL, 'DC차단기', '민병은', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (21, 'A020', '피코센서', NULL, NULL, NULL, '센서', '김경학', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (22, 'A021', '해울이앤지', NULL, NULL, NULL, '기상센서', '박태환', NULL, NULL, NULL, NULL);
INSERT INTO clients (id, code, name, business_no, representative, business_type, business_item, manager, phone, email, address, note) VALUES (23, 'A022', '티오시스', NULL, NULL, NULL, 'Hi-Box', '이태우', NULL, NULL, NULL, NULL);

INSERT INTO products (id, code, name, unit, note) VALUES (1, '시트위저드', '시트위저드', '시트위저드', '시트위저드');
INSERT INTO products (id, code, name, unit, note) VALUES (2, 'BH01', 'BH-KNCF-10-4', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (3, 'BH02', 'BH-KNCF-10-8', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (4, 'BH03', 'BH-KNCF-10-12', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (5, 'BH04', 'BH-KNCF-10-16', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (6, 'BH05', 'BH-KNCF-10-20', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (7, 'BH06', 'BH-KNA-10-16', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (8, 'BH07', 'BH-KNA-10-20', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (9, 'BH08', 'BH-KNCW-15-24', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (10, 'BH09', 'BH-KNCS-10-20', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (11, 'BH10', 'BH-KNCS-10-16', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (12, 'BH11', 'BH-KNCM-10-12', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (13, 'BH12', 'BH-KNCW-15-24_HC', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (14, 'BH13', 'BH-KNCF-15-20 (퓨즈20A)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (15, 'BH14', 'BH-KDCF-15-18_SMG1', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (16, 'BH15', 'BH-KDCF-15-16_SMG1', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (17, 'BH16', 'BH-KNCF-15-16 (퓨즈20A)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (18, 'BH17', 'BH-KDCW-15-20_SMG2-2', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (19, 'BH18', 'BH-KDCW-15-16_SMG2-1', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (20, 'BH19', 'BH-KDCW-15-20_SMG3', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (21, 'BH20', 'BH-KDCW-15-18_SMG3', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (22, 'BH21', 'BH-KNCS-10-4_4SR', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (23, 'BH22', 'BH-KDCF-15-30_GH', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (24, 'BH23', 'BH-KDCF-15-28_GH', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (25, 'BH24', 'BH-KDCF-15-24_GH', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (26, 'BH25', 'BH-KNCF-15-16_300-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (27, 'BH26', 'BH-KNCF-15-20_400-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (28, 'BH27', 'BH-KNCF-15-24_500-30', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (29, 'BH28', 'BH-KNA-15-3SR', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (30, 'BH29', 'BH-KDCF-15-18_IWH', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (31, 'BH30', 'BH-KNCF-15-8_200-30', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (32, 'BH31', 'BH-KNCF-15-12_275-30', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (33, 'BH32', 'BH-KNA-15-18_TACE', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (34, 'BH33', 'BH-KNA-15-22_TACE', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (35, 'BH34', 'BH-KNCF-15-22_DH-400-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (36, 'BH35', 'BH-KNCF-15-26_DH-400-20', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (37, 'BH36', 'BH-KNCF-15-21_DH-400-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (38, 'BH37', 'BH-KNCF-15-25_DH-400-20', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (39, 'BH38', 'BH-KNCF-15-26_DH-500-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (40, 'BH39', 'BH-KNCF-15-25_DH-500-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (41, 'BH40', 'BH-KNCM-15-8_200-25', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (42, 'BH41', 'BH-KNCF-10-4_US-80-25 (유사)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (43, 'BH42', 'BH-KNCF-15-8_US-160-25 (유사)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (44, 'BH43', 'BH-KNCF-15-12_US-250-25 (유사)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (45, 'BH44', 'BH-KNCM-10-12_US-250-25 (유사)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (46, 'BH45', 'BH-CS-RSD(열분포)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (47, 'BH46', 'BH-KDCF-15-18-IHD', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (48, 'BH47', 'BH-KNA-3SR_US-30-15(유사)', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (49, 'BH48', 'BH-KNCF-15-18_DJSLF-300-30', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (50, 'BH49', 'BH-KNCF-15-20_DJSLF-400-30', '면', NULL);
INSERT INTO products (id, code, name, unit, note) VALUES (51, 'BH50', 'BH-KNA-15-12SR', '면', NULL);

INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (1, '시트위저드', '시트위저드', '시트위저드', 1111111, 1111111, '시트위저드');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (2, 'A01', 'LS UTD 1500V 200A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (3, 'A02', 'LS UTD 1500V 250A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (4, 'A03', 'LS UTD 1500V 275A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (5, 'A04', 'LS UTD 1500V 300A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (6, 'A05', 'LS UTD 1500V 400A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (7, 'A06', 'LS UTD 1500V 450A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (8, 'A07', 'LS UTD 1500V 500A', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (9, 'A08', 'LS 1500V 200~250A 방열판', 'EA', 0, 10, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (10, 'A09', 'LS 1500V 275~450A 방열판', 'EA', 0, 10, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (11, 'A10', 'LS 1500V 450~600A 방열판', 'EA', 0, 10, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (12, 'A11', 'LS 1000V 63A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (13, 'A12', 'LS 1000V 80A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (14, 'A13', 'LS 1000V 125A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (15, 'A14', 'LS 1000V 200A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (16, 'A15', 'LS 1000V 250A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (17, 'A16', 'LS 1000V 300A - FMU', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (18, 'A17', 'LS 화재트립코일 (1000V)', 'EA', 0, 20, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (19, 'A18', 'LS 화재트립코일 (1500V)', 'EA', 0, 20, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (20, 'A19', 'LS 소형차단기 트립코일 SHT-H', 'EA', 0, 50, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (21, 'A20', 'LS 소형차단기 BK63H_DC_4P_16A', 'EA', 0, 50, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (22, 'A21', 'AX.TD160-TS800 : 1000(V) 보조접점', 'EA', 0, 5, '발주 후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (23, 'C01', '현대차단기 100A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (24, 'C02', '현대차단기 160A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (25, 'C03', '현대차단기 200A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (26, 'C04', '현대차단기 250A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (27, 'C05', '현대차단기 300A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (28, 'C06', '현대차단기 400A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (29, 'C07', '현대차단기 500A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (30, 'C08', '현대차단기 방열판 컴먼부스바 160~250A', 'EA', 0, 10, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (31, 'C09', '현대차단기 트립코일 160~250A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (32, 'C10', '현대차단기 방열판 컴먼부스바 400~500A', 'EA', 0, 10, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (33, 'C11', '현대차단기 트립코일 400~500A', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (34, 'D01', '1000V 스텐다드 20CH 부스바', 'SET', 0, 3, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (35, 'D02', '1000V 스텐다드 16CH 부스바', 'SET', 0, 3, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (36, 'D03', '1000V 스텐다드 12CH 부스바', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (37, 'D04', '1000V 스텐다드 8CH 부스바', 'SET', 0, 3, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (38, 'D05', '1000V 스텐다드 4CH 부스바', 'SET', 0, 3, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (39, 'D06', '1000V 차단기 부스바 6T(방열판) 20CH', 'EA', 0, 50, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (40, 'D07', '1000V 차단기 부스바 5T(방열판)', 'EA', 0, 50, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (41, 'D08', '차단기 방열판', 'EA', 0, 50, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (42, 'D09', '은 접지 부스바', 'EA', 0, 30, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (43, 'D10', '1500V 스텐다드 24CH 부스바', 'SET', 0, 3, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (44, 'D11', '1500V 스텐다드 20CH 부스바', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (45, 'D12', '1500V 스텐다드 16CH 부스바', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (46, 'D13', '1500V 스텐다드 12CH 부스바', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (47, 'D14', '1500V 스텐다드 8CH 부스바', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (48, 'B01', '썬트리 차단기', 'EA', 0, 40, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (49, 'B02', '친트 차단기', 'EA', 0, 40, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (50, 'E01', 'DC SPD (1000V) 피닉스', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (51, 'E02', 'DC SPD (1000V)-접점 피닉스', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (52, 'E03', 'DC SPD (1500V) 피닉스', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (53, 'E04', 'DC SPD (1500V) WR-T2-DC', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (54, 'E05', 'AC SPD', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (55, 'E06', '통신 SPD', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (56, 'E07', 'AC & 통신 SPD 일체형', 'EA', 0, 30, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (57, 'F01', '1000V 퓨즈 홀더', 'EA', 0, 100, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (58, 'F02', '1500V 퓨즈 홀더', 'EA', 0, 300, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (59, 'F03', '1500V 퓨즈홀더 CFPV-63L', 'EA', 0, 50, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (60, 'F04', 'FUSE 1A (1000V)', 'EA', 0, 50, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (61, 'F05', 'FUSE 15A (1000V)', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (62, 'F06', 'FUSE 20A (1000V)', 'EA', 0, 100, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (63, 'F07', 'FUSE 25A (1000V)', 'EA', 0, 100, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (64, 'F08', 'FUSE 20A (1500V)', 'EA', 0, 100, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (65, 'F09', 'FUSE 25A (1500V)', 'EA', 0, 200, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (66, 'F10', 'FUSE 30A (1500V)', 'EA', 0, 200, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (67, 'G01', 'BH-PMB-2-XD', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (68, 'G02', 'BH-NCB-2-OF(CT)', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (69, 'G03', 'BH-CTB-2', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (70, 'G04', 'BH-VCTB-2', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (71, 'G05', 'BH-CM1528', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (72, 'G06', 'BH-CM1528 SD', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (73, 'G07', 'BH-CM1530', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (74, 'G08', 'BH-FRC', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (75, 'G09', 'BH-FRC-2', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (76, 'G10', 'BH-SBC', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (77, 'G11', 'BH-ETH', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (78, 'G12', 'BH-WC4P', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (79, 'G13', 'BH-SDU', 'EA', 0, 15, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (80, 'G14', 'BH-TMC', 'EA', 0, 60, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (81, 'H01', 'LRS-200-24', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (82, 'H02', 'LRS-350-24', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (83, 'H03', 'MDR-20-24', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (84, 'H04', 'SMPS(75W)', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (85, 'H05', '파워캅 SMPS', 'EA', 0, 5, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (86, 'I01', '내부온도센서 1528용 하얀색 커넥터', 'EA', 0, 10, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (87, 'I02', '내부온도센서 1530용 펜홀 터미널', 'EA', 0, 10, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (88, 'J01', '화재센서', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (89, 'J02', '화재센서_브라켓', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (90, 'K01', '전압 케이블 1M', 'EA', 0, 15, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (91, 'K02', '전압 케이블 2M', 'EA', 0, 15, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (92, 'K03', '전압 케이블 2.5M', 'EA', 0, 15, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (93, 'K04', '전압 케이블 3M', 'EA', 0, 15, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (94, 'K05', '전류 케이블 2.5M 4P', 'EA', 0, 60, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (95, 'K06', '전류 케이블 2.5M 6P', 'EA', 0, 60, '발주후 3주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (96, 'L01', 'KEL-DPF 40', 'EA', 0, 30, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (97, 'L02', 'KEL-DPF 32', 'EA', 0, 60, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (98, 'L03', 'KEL-DPF 25', 'EA', 0, 30, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (99, 'M01', 'DTS-M 40', 'EA', 0, 50, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (100, 'M02', 'DTS-M 32', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (101, 'M03', 'DTS-M 25', 'EA', 0, 200, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (102, 'M04', 'DMTS-M 25(3홀 원형)', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (103, 'M05', 'DHSS-M50', 'EA', 0, 30, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (104, 'M06', 'DHSS-M60', 'EA', 0, 30, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (105, 'N01', '노드락 Ø4', 'EA', 0, 400, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (106, 'N02', '노드락 Ø5', 'EA', 0, 400, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (107, 'N03', '노드락 Ø8', 'EA', 0, 400, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (108, 'N04', '노드락 Ø10', 'EA', 0, 400, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (109, 'O01', 'AC조작차단기(BK63H)', 'EA', 0, 20, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (110, 'O02', '누전차단기(32GRhS 15A 30mA)', 'EA', 0, 5, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (111, 'O03', '아크차단기', 'EA', 0, 10, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (112, 'P01', '1500V 4P 단자대 (KTB1-06004Z)', 'EA', 0, 20, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (113, 'P02', '1500V 3P 단자대 (KTB1-06003Z)', 'EA', 0, 20, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (114, 'P03', 'SHT-20-4P AC단자대', 'EA', 0, 20, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (115, 'P04', 'SHT-20-6P 통신단자대', 'EA', 0, 20, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (116, 'Q01', '다이오드 1000V', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (117, 'Q02', 'NELL 다이오드 1500V', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (118, 'Q03', 'MDK 100-18(100A, 1800V)', 'EA', 0, 100, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (119, 'D15', '1500V 21CH 9종 부스바 DH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (120, 'D16', '1500V 22CH 9종 부스바 DH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (121, 'D17', '1500V 25CH 13종 부스바 DH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (122, 'D18', '1500V 26CH 13종 부스바 DH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (123, 'D19', '1500V 18CH 10종 부스바 IWH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (124, 'D20', '1500V 18CH 10종 부스바 IHD', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (125, 'D21', '1500V 18CH 9종 부스바 DJSLF', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (126, 'D22', '1500V 20CH 9종 부스바 DJSLF', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (127, 'D23', '1500V 24CH 10종 부스바 GH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (128, 'D24', '1500V 28CH 10종 부스바 GH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (129, 'D25', '1500V 30CH 10종 부스바 GH', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (130, 'D26', '1500V 18CH 8종 부스바 TACE', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (131, 'D27', '1500V 22CH 8종 부스바 TACE', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (132, 'D28', '1500V 18CH 8종 부스바 SMG1', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (133, 'D29', '1500V 16CH 8종 부스바 SMG1', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (134, 'D30', '1500V 16CH 8종 부스바 SMG2-1', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (135, 'D31', '1500V 20CH 8종 부스바 SMG2-2', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (136, 'D32', '1500V 18CH 8종 부스바 SMG3', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (137, 'D33', '1500V 20CH 8종 부스바 SMG3', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (138, 'D34', '1500V 24CH 6종 부스바 HC', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (139, 'D35', '1500V 16CH 8종 부스바 (20A)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (140, 'D36', '1500V 20CH 8종 부스바 (20A)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (141, 'D37', '1000V 4CH 8종 부스바 (US-25A)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (142, 'D38', '1500V 8CH 9종 부스바 (US-25A)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (143, 'D39', '1500V 12CH 9종 부스바 (US-25A)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (144, 'D40', '1500V 4CH 7종 부스바 (우수조달 규격 추가)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (145, 'D41', '1500V 8CH 9종 부스바 (우수조달 규격 추가)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (146, 'D42', '1500V 12CH 9종 부스바 (우수조달 규격 추가)', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (147, 'D43', '1500V 8CH 9종 부스바 (일체형) (우수조달, MAS)', 'SET', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (148, 'R01', '1500V 30A 3P 개폐기', 'EA', 0, 5, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (149, 'R02', '1500V 30A 4P 개폐기', 'EA', 0, 5, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (150, 'R03', '1500V 320A 개폐기', 'EA', 0, 2, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (151, 'R04', '1500V 400A 개폐기', 'EA', 0, 2, '발주후 5주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (152, 'P05', '피닉스컨텍 T/B (ST-6)', 'EA', 0, 50, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (153, 'P06', '피닉스컨텍 T/B (D-ST-6)_커버', 'EA', 0, 5, '발주후 2주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (154, 'D44', '동 접지부스바 3P', 'EA', 0, 20, '발주후 1주');
INSERT INTO materials (id, code, name, unit, initial_stock, safety_stock, note) VALUES (155, 'F11', 'FUSE 15A (1500V)', 'EA', 0, 30, '발주후 1주');

-- Sequence updates
SELECT setval('clients_id_seq', (SELECT MAX(id) FROM clients));
SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));
SELECT setval('materials_id_seq', (SELECT MAX(id) FROM materials));
