-- 1. 거래처 테이블
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  business_no TEXT,
  representative TEXT,
  business_type TEXT,
  business_item TEXT,
  manager TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 품목 테이블
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'EA',
  initial_stock NUMERIC DEFAULT 0,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 자재 테이블
CREATE TABLE materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'EA',
  initial_stock NUMERIC DEFAULT 0,
  safety_stock NUMERIC DEFAULT 0,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BOM (구성 자재) 테이블
CREATE TABLE bom (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  material_id BIGINT REFERENCES materials(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 자재 입출고 거래 내역
CREATE TABLE material_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  material_id BIGINT REFERENCES materials(id) ON DELETE CASCADE,
  product_shipment_id BIGINT REFERENCES product_shipments(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('in', 'out')),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 품목 출고 내역 (등록 시 자재 자동 차감 트리거용/로직용)
CREATE TABLE product_shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 프로젝트 관리 (완제품 납품 현황)
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name TEXT NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  spec TEXT,
  status TEXT DEFAULT '제작중',
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. 품목 출고 시 수기 입력용 납품업체 필드 추가
ALTER TABLE product_shipments ADD COLUMN delivery_company TEXT;

-- 9. 품목 출고 시 자동차감된 자재 내역 연동 (자동 삭제용)
ALTER TABLE material_transactions ADD COLUMN product_shipment_id BIGINT REFERENCES product_shipments(id) ON DELETE CASCADE;

-- 10. 시스템 작업 로그 (Audit Log)
CREATE TABLE system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL,
  action_type TEXT NOT NULL,
  target_name TEXT,
  details TEXT NOT NULL,
  user_name TEXT DEFAULT '관리자',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. 프로젝트 제작 수량 컬럼 및 자재 차감 외래키 연동
ALTER TABLE projects ADD COLUMN IF NOT EXISTS quantity NUMERIC DEFAULT 1;
ALTER TABLE material_transactions ADD COLUMN IF NOT EXISTS project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE;

-- 12. 자재 테이블에 현장 자재명(별칭) 컬럼 추가
ALTER TABLE materials ADD COLUMN IF NOT EXISTS field_name TEXT;


