-- 1. 거래처 테이블
CREATE TABLE clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  business_no TEXT,
  representative TEXT,
  business_type TEXT,
  business_item TEXT,
  manager TEXT,
  phone TEXT,
  email TEXT,
  address TEXT,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 품목 테이블
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'EA',
  initial_stock NUMERIC DEFAULT 0,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 자재 테이블
CREATE TABLE materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'EA',
  initial_stock NUMERIC DEFAULT 0,
  safety_stock NUMERIC DEFAULT 0,
  note TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BOM (구성 자재) 테이블
CREATE TABLE bom (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  material_id BIGINT REFERENCES materials(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 자재 입출고 거래 내역
CREATE TABLE material_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  material_id BIGINT REFERENCES materials(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('in', 'out')),
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 품목 출고 내역 (등록 시 자재 자동 차감 트리거용/로직용)
CREATE TABLE product_shipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
